[package]
name = "clash"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1", features = ["full"] }
thiserror = "1.0"
async-trait = "0.1"
anyhow = "1.0"
futures = "0.3"
bytes = "1.1"
log = "0.4"
fern = { version="0.6", features = ["colored"] }
chrono = "0.4"
ipnet = "2.5"
url = "2.2"
regex = "1"
state = "0.5"
byteorder = "1.4"
lru-cache = "0.1"
hyper = { version = "0.14", features = ["http1","http2","client"] }
tower = { version = "0.4", features = ["util"] }


serde = { version = "1.0", features=["derive"] }
serde_yaml = "0.9"

trust-dns-client = "0.22"
trust-dns-server = "0.22"
trust-dns-resolver = "0.22"
trust-dns-proto = "0.22"
rand = "0.8"
async_singleflight = "0.5.0"
get_if_addrs = "0.5.3"

socket2 = "0.4.4"

async-socks5 = "0.5"

[dev-dependencies]
tempfile = "3.3"
