[package]
name = "clash"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "clash"
path = "src/main.rs"

[dependencies]
clap = { version = "3.2.20", features = ["derive"] }

clash_lib = { path = "../clash_lib" }