[package]
name = "clash"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1", features = ["full"] }
thiserror = "1.0"
async-trait = "0.1"
anyhow = "1.0"
futures = "0.3"
bytes = "1.1"
log = "0.4"
fern = { version="0.6", features = ["colored"] }
chrono = "0.4"
ipnet = "2.5"
url = "2.2"
regex = "1"
state = "0.5"
byteorder = "1.4"
lru_time_cache = "0.11"
hyper = { version = "0.14", features = ["http1","http2","client"] }
tower = { version = "0.4", features = ["util"] }
libc = "0.2"
network-interface = "0.1"


serde = { version = "1.0", features=["derive"] }
serde_yaml = "0.9"

trust-dns-client = "0.22"
trust-dns-proto = { version = "0.22", features = ["dns-over-rustls", "dns-over-https-rustls"]}
# DoH
rustls = "0.20"
webpki-roots = "0.22"
dhcproto = "0.8"

rand = "0.8"

socket2 = "0.4"

async-socks5 = "0.5"

[dev-dependencies]
tempfile = "3.3"
ctor = "0.1"
env_logger = "0.9"
