version: "3.9"

services:
  shadowsocks:
    build: ./ss
    ports:
      - "8388:8388/tcp"
      - "8388:8388/udp"
    command: ["-s", "ss://AEAD_AES_256_GCM:password@:8388", "-udp", "-verbose"]
    restart: unless-stopped

  v2ray-vmess:
    image: v2fly/v2fly-core
    ports:
      - "8443-8444:8443-8444/tcp"
      - "16823-16824:16823-16824/udp"
    command: ["run", "-c", "/etc/v2ray/config.json"]
    volumes:
      - type: bind
        source: ./v2ray/config.json
        target: /etc/v2ray/config.json
      - type: bind
        source: ./v2ray/cert.pem
        target: /etc/v2ray/v2ray.crt
      - type: bind
        source: ./v2ray/key.pem
        target: /etc/v2ray/v2ray.key