[package]
name = "clash_ffi"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clash_lib = { path = "../clash_lib" }

[build-dependencies]

[lib]
name = "libclash"
crate-type = ["staticlib", "cdylib"]